Improved plugin management

diff --git a/.config/zsh/zsh-functions b/.config/zsh/zsh-functions
--- a/.config/zsh/zsh-functions
+++ b/.config/zsh/zsh-functions
@@ -1,15 +1,21 @@
 # Function to source files if they exist
-function zsh_add_file() {
-    [ -f "$ZDOTDIR/$1" ] && source "$ZDOTDIR/$1"
+function add_file() {
+    if [ -f "$ZDOTDIR/$1" ]; then
+        source "$ZDOTDIR/$1" || { echo "Error: Failed to source file $ZDOTDIR/$1" >&2; return 1; }
+    else
+        echo "Error: File not found: $1" >&2; return 1
+    fi
+
 }
 
 # Function to add plugins if they exist
-function zsh_add_plugin() {
+function add_plugin() {
     PLUGIN_NAME=$(echo $1 | cut -d "/" -f 2)
     if [ -d "$ZDOTDIR/plugins/$PLUGIN_NAME" ]; then
-        zsh_add_file "plugins/$PLUGIN_NAME/$PLUGIN_NAME.plugin"
-        zsh_add_file "plugins/$PLUGIN_NAME/$PLUGIN_NAME.zsh"
-#    else
-#        git clone "https://github.com/$1.git" "$ZDOTDIR/plugins"
+        add_file "plugins/$PLUGIN_NAME/$PLUGIN_NAME.plugin.zsh"
+        add_file "plugins/$PLUGIN_NAME/$PLUGIN_NAME.zsh"
+    else
+        git clone "https://github.com/$1.git" "$ZDOTDIR/plugins/$PLUGIN_NAME" || { echo "Error: Failed to clone repository $1"; return 1; }
+        add_plugin $1
     fi
 }
