zsh-functions: add_plugin is now add_plugins and can take multiple arguments

diff --git a/zsh/zsh-functions b/zsh/zsh-functions
--- a/zsh/zsh-functions
+++ b/zsh/zsh-functions
@@ -9,16 +9,20 @@ function add_file() {
 }
 
 # Function to add plugins if they exist
-function add_plugin() {
-    local plugin_name
-    plugin_name="${1#*/}"
-    if [ -d "$ZDOTDIR/plugins/$plugin_name" ]; then
-        add_file "plugins/$plugin_name/$plugin_name.plugin.zsh"
-        add_file "plugins/$plugin_name/$plugin_name.zsh"
-    else
-        git clone "https://github.com/$1.git" "$ZDOTDIR/plugins/$plugin_name" || { echo "Error: Failed to clone repository $1"; return 1; }
-        add_plugin $1
-    fi
+function add_plugins() {
+    local plugin repo plugin_name
+    for plugin in $@; do
+        repo="$plugin"
+        plugin_name="${plugin#*/}"
+        if [ -d "$ZDOTDIR/plugins/$plugin_name" ]; then
+            add_file "plugins/$plugin_name/$plugin_name.plugin.zsh"
+            add_file "plugins/$plugin_name/$plugin_name.zsh"
+        else
+            git clone "https://github.com/$repo.git" "$ZDOTDIR/plugins/$plugin_name" || { echo "Error: Failed to clone repository $plugin"; return 1; }
+            add_plugin "$repo"
+            echo "Success: $repo"
+        fi
+    done
 }
 
 # Function to update plugins
